# Mehedi H Shohag
## CSC 301 - M
## Date: 10/06/2021
## Assignment 3

In [1]:
#importing required modules
import math
import time
import pandas as pd

In [2]:
#implementation of naive sum
#calculate the sum and the time elapsed

def naive_Sum(power, sqrt23):
    Sum = 0
    start_time = time.time()
    for i in range(power):
        Sum += sqrt23
    end_time = time.time()
    
    elapsed_time = end_time - start_time
    
    return Sum, elapsed_time

In [3]:
#implementation of compensated sum
#calculate the sum and the time elapsed

def compensated_Sum(power, sqrt23):
    start_time = time.time()
    Sum = 0
    e = 0
    for i in range(power):
        temp = Sum
        y = sqrt23 + e
        Sum = temp + y
        e = (temp - Sum) + y
    Sum += e
    end_time = time.time()
    
    elapsed_time = end_time - start_time
    
    return Sum, elapsed_time

In [8]:
def main():
    naiveSum=list()
    compensatedSum=list()
    
    for i in range(3,9):
        power=pow(10,i)
        sq23=math.sqrt(23)
        exact_value=power * sq23
        
        naive_sum, naive_sum_time = naive_Sum(power, sq23)
        naive_absolute_error = abs(exact_value - naive_sum)
        naive_relative_error = (naive_absolute_error / exact_value) * 100
        naiveSum.append({'N': '10^'+ str(i),
                         'Exact Value ':exact_value,
                         'Naive Sum': str(naive_sum),
                         'Time Elapsed': naive_sum_time, 
                         'Naive Absolute Error': naive_absolute_error,
                         'Naive Relative Error': naive_relative_error})
        
        compensated_sum, compensated_time = compensated_Sum(power, sq23)
        compensated_absolute_error = abs(exact_value - compensated_sum)
        compensated_relative_error = (compensated_absolute_error / exact_value) * 100
        compensatedSum.append({'N': '10^' + str(i),
                               'Exact Value: ':exact_value,
                               'Compensated Sum': str(compensated_sum),
                               'Time Elapsed': compensated_time,
                               'Compensated Absolute Error': compensated_absolute_error,
                               'Compensated Relative Error': compensated_relative_error})
        
    naiveSum_df = pd.DataFrame(naiveSum,index=[1,2,3,4,5,6])
    display(naiveSum_df)
    print('---------------------------------------------------------------------------------')
    compensatedSum_df = pd.DataFrame(compensatedSum,index=[1,2,3,4,5,6])
    display(compensatedSum_df)

In [9]:
main()

,N,Exact Value,Naive Sum,Time Elapsed,Naive Absolute Error,Naive Relative Error
1,10^3,4.795832e+03,4795.831523312701,0.000000,1.728040e-11,3.603212e-13
2,10^4,4.795832e+04,47958.315233122565,0.000000,4.627509e-09,9.649023e-12
3,10^5,4.795832e+05,479583.1523311837,0.004000,8.818461e-08,1.838776e-11
4,10^6,4.795832e+06,4795831.523305233,0.031476,7.486902e-06,1.561127e-10
5,10^7,4.795832e+07,47958315.23712847,0.317619,4.001275e-03,8.343235e-09
6,10^8,4.795832e+08,479583151.50250727,4.359339,8.287646e-01,1.728094e-07

---------------------------------------------------------------------------------

,N,Exact Value:,Compensated Sum,Time Elapsed,Compensated Absolute Error,Compensated Relative Error
1,10^3,4.795832e+03,4795.831523312719,0.000000,0.0,0.0
2,10^4,4.795832e+04,47958.31523312719,0.000999,0.0,0.0
3,10^5,4.795832e+05,479583.1523312719,0.010662,0.0,0.0
4,10^6,4.795832e+06,4795831.52331272,0.086651,0.0,0.0
5,10^7,4.795832e+07,47958315.23312719,0.977662,0.0,0.0
6,10^8,4.795832e+08,479583152.3312719,12.084927,0.0,0.0

# Analysis
After calculating the results we can observe that, as the N increases the time to calculate the sum also increases. But compare to Naive and Compensated, the Naive sum is much faster then compensated sum. Because there are more calculation and steps which make compensated sum a bit slower.<br>
When we look at the errors, the compensated sum is more accurate then naive sum. Compensated sum gives accurate result.And when we look at the absolute and relative errors of the Compensated sum we can see that it gives no error which is 0.And it's obvious we learned from the class lecture that, the compensated summation is a recursive summation that diminishes rounding errors.But on the other hand for the Naive sum as N increases the absolute and relative error increases.<br>
So, we can conclude that, compensated summation is more accurate whereas naive summation is faster.